os: osx
language: python
python:
    - 3.7.6
before_install:
    - brew install libomp openblas
    - echo "export LDFLAGS='-L/usr/local/opt/openblas/lib'" >> ~/.bash_profile
    - echo "export CPPFLAGS='-I/usr/local/opt/openblas/include'" >> ~/.bash_profile
    - source ~/.bash_profile
install:
    - pip install numpy scipy cython
    - pip install git+https://github.com/satopirka/cymf
