version: 2
jobs:
  build:
    macos: # executor type
      xcode: "9.0"
    working_directory: ~/circleci-fastmf
    docker:
      - image: circleci/python:3.7.4  # ビルドジョブのプライマリコンテナ
    steps:
      - checkout  # ソースコードを作業ディレクトリにチェックアウトします
      - run:
          command: |  
            sudo pip install -r requirements.txt
            