version: 2
jobs:
  build:
    working_directory: ~/circleci-fastmf
    docker:
      - image: circleci/python:3.7.4  # ビルドジョブのプライマリコンテナ
    steps:
      - checkout  # ソースコードを作業ディレクトリにチェックアウトします
      - run:
          command: |
            git clone git://github.com/yyuu/pyenv.git ~/.pyenv
      - run:
          command: |
            echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $BASH_ENV
            echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
            pyenv install miniconda3-latest
            pyenv global miniconda3-latest
            pyenv rehash
            eval "$(pyenv init -)"
            conda install -y -c conda-forge openmp
            pip install -r requirements.txt
            make
