version: 2
jobs:
  "python374":
    working_directory: ~/circleci-fastmf
    docker:
      - image: circleci/python:3.7.4  # ビルドジョブのプライマリコンテナ
    steps:
      - checkout  # ソースコードを作業ディレクトリにチェックアウトします
      - run:
          command: |  
            sudo pip install -r requirements.txt
  "gcc7":
    working_directory: ~/circleci-fastmf
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
        command: |
          make

workflows:
  version: 2
  build:
    jobs:
      - "py374"
      - "gcc7"
